export const KILLERS = [
  { name: "Trapper | Охотник", avatar: "/images/avatars/trapper.webp" },
  { name: "Wraith | Призрак", avatar: "/images/avatars/wraith.webp" },
  { name: "Hillbilly | Деревенщина", avatar: "/images/avatars/billy.webp" },
  { name: "Nurse | Медсестра", avatar: "/images/avatars/nurse.webp" },
  { name: "The Shape | Тень", avatar: "/images/avatars/mayers.webp" },
  { name: "Hag | Ведьма", avatar: "/images/avatars/hug.webp" },
  { name: "The Doctor | Доктор", avatar: "/images/avatars/doctor.webp" },
  { name: "Huntress | Охотница", avatar: "/images/avatars/huntress.webp" },
  { name: "The Cannibal | Каннибал", avatar: "/images/avatars/bubba.webp" },
  { name: "The Nightmare | Кошмар", avatar: "/images/avatars/freddy.webp" },
  { name: "The Pig | Свинья", avatar: "/images/avatars/pig.webp" },
  { name: "The Clown | Клоун", avatar: "/images/avatars/clown.webp" },
  { name: "The Spirit | Дух", avatar: "/images/avatars/spirit.webp" },
  { name: "The Legion | Легион", avatar: "/images/avatars/legion.webp" },
  { name: "The Plague | Чума", avatar: "/images/avatars/plug.webp" },
  { name: "The Ghost Face | Гоуст Фейс", avatar: "/images/avatars/ghostface.webp" },
  { name: "The Demogorgon | Демогоргон", avatar: "/images/avatars/demo.webp" },
  { name: "The Oni | Они", avatar: "/images/avatars/oni.webp" },
  { name: "The Deathslinger | Стрелок", avatar: "/images/avatars/gunslinger.webp" },
  { name: "The Executioner | Палач", avatar: "/images/avatars/pyramidhead.webp" },
  { name: "The Blight | Мор", avatar: "/images/avatars/blight.webp" },
  { name: "The Twins | Близнецы", avatar: "/images/avatars/twins.webp" },
  { name: "The Trickster | Трюкач", avatar: "/images/avatars/trickster.webp" },
  { name: "The Nemesis | Немезис", avatar: "/images/avatars/nemesis.webp" },
  { name: "The Cenobite | Сенобит", avatar: "/images/avatars/pinhead.webp" },
  { name: "The Artist | Художница", avatar: "/images/avatars/artist.webp" },
  { name: "The Onryō | Онрё", avatar: "/images/avatars/sadako.webp" },
  { name: "The Dredge | Грязь", avatar: "/images/avatars/dredge.webp" },
  { name: "The Mastermind | Кукловод", avatar: "/images/avatars/wesker.webp" },
  { name: "The Knight | Рыцарь", avatar: "/images/avatars/knight.webp" },
  { name: "The Skull Merchant | Торговка черепами", avatar: "/images/avatars/skullmerchant.webp" },
  { name: "The Singularity | Сингулярность", avatar: "/images/avatars/singularity.webp" },
  { name: "The Xenomorph | Ксеноморф", avatar: "/images/avatars/xeno.webp" },
  { name: "The Good Guy | Хороший Парень", avatar: "/images/avatars/chakky.webp" },
  { name: "The Unknown | Неведомое", avatar: "/images/avatars/error.webp" },
  { name: "The Lich | Лич", avatar: "/images/avatars/vekna.webp" },
  { name: "The Dark Lord | Темный Властелин", avatar: "/images/avatars/drakula.webp" },
  { name: "The Houndmaster | Егерь", avatar: "/images/avatars/psina.webp" },
];
