export const PERKS = [
  { ru: "Нетерпимость", en: "Agitation" },
  { ru: "Зверская сила", en: "Brutal Strength" },
  { ru: "Пугающее присутствие", en: "Fearmonger" },
  { ru: "Детище тьмы", en: "Dark Devotion" },
  { ru: "Ищейка", en: "Detective's Hunch" },
  { ru: "Хищник", en: "Predator" },
  { ru: "Стойкий", en: "Tenacity" },
  { ru: "Детище света", en: "Lightbringer" },
  { ru: "Умелец", en: "Saboteur" },
  { ru: "Стридор", en: "Stridor" },
  { ru: "Танатофобия", en: "Thanatophobia" },
  { ru: "Зов Медсестры", en: "Nurse's Calling" },
  { ru: "Оставьте лучшее напоследок", en: "Save the Best for Last" },
  { ru: "Угасающий свет", en: "Fading Light" },
  { ru: "Поиграть со своей жертвой", en: "Play with Your Food" },
  { ru: "Порча: погибель", en: "Hex: Ruin" },
  { ru: "Порча: пожирание надежды", en: "Hex: Devour Hope" },
  { ru: "Порча: третья печать", en: "Hex: Third Seal" },
  { ru: "Слежка и наказание", en: "Surveillance and Punishment" },
  { ru: "Перегрузка", en: "Overcharge" },
  { ru: "Невыносимое присутствие", en: "Unnerving Presence" },
  { ru: "Территориальный императив", en: "Territorial Imperative" },
  { ru: "Порча: колыбельная охотницы", en: "Hex: Huntress's Lullaby" },
  { ru: "Хищный зверь", en: "Savage Beast" },
  { ru: "Барбекю и чили", en: "BBQ & Chili" },
  { ru: "Гибель Франклина", en: "Franklin's Demise" },
  { ru: "Нокаут", en: "Knock Out" },
  { ru: "Яркое пламя", en: "Bright Flame" },
  { ru: "Помни меня", en: "Remember Me" },
  { ru: "Кровавый смотритель", en: "Blood Warden" },
  { ru: "Выбор за тобой", en: "You're On Your Own" },
  { ru: "Наблюдение", en: "Monitoring and Abuse" },
  { ru: "Секущий крюк: секрет палача", en: "Hooked on You" },
  { ru: "Чертик из табакерки", en: "Jack-in-the-Box" },
  { ru: "Клоунофобия", en: "Clownophobia" },
  { ru: "Розыгрыш", en: "Prankster" },
  { ru: "Ненависть", en: "Hate" },
  { ru: "Порча: проклятая земля", en: "Hex: Cursed Ground" },
  { ru: "Ярость духа", en: "Spirit Fury" },
  { ru: "Разлад", en: "Discordance" },
  { ru: "Железная дева", en: "Iron Maiden" },
  { ru: "Безумное упорство", en: "Mad Grit" },
  { ru: "Темная преданность", en: "Dark Devotion" },
  { ru: "Вмешательство скверны", en: "Corrupt Intervention" },
  { ru: "Заразительный ужас", en: "Infectious Fright" },
  { ru: "Скрытная погоня", en: "Stealth Pursuit" },
  { ru: "Чуткий слух", en: "Keen Hearing" },
  { ru: "Пугающая тряска", en: "Scary Shake" },
  { ru: "Жестокая изоляция", en: "Brutal Isolation" },
  { ru: "Разрушитель разума", en: "Mindbreaker" },
  { ru: "Выброс", en: "Eruption" },
  { ru: "Тактика зансин", en: "Zanshin Tactics" },
  { ru: "Отзвук крови", en: "Blood Echo" },
  { ru: "Возмездие", en: "Vengeance" },
  { ru: "Порча: кара", en: "Hex: Retribution" },
  { ru: "Аварийная кнопка", en: "Emergency Button" },
  { ru: "Знаток техники", en: "Technician" },
  { ru: "Тропа терзаний", en: "Trail of Torment" },
  { ru: "Принудительная мера", en: "Coercive Measure" },
  { ru: "Смертельные узы", en: "Deadly Bonds" },
  { ru: "Порча: благоволение крови", en: "Hex: Blood Favor" },
  { ru: "Порча: не-смерть", en: "Hex: Undying" },
  { ru: "Драконья хватка", en: "Dragon's Grip" },
  { ru: "Добивание", en: "Merciless" },
  { ru: "Скопидом", en: "Scavenger" },
  { ru: "Притеснение", en: "Oppression" },
  { ru: "Фанатение", en: "Frenzy" },
  { ru: "Порча: контроль толпы", en: "Hex: Crowd Control" },
  { ru: "Выхода нет", en: "No Way Out" },
  { ru: "Подрыв", en: "Detonate" },
  { ru: "Истерия", en: "Hysteria" },
  { ru: "Преследователь-убийца", en: "Killer Instinct" },
  { ru: "Мертвая хватка", en: "Deadlock" },
  { ru: "Порча: игрушка", en: "Hex: Toy" },
  { ru: "Секущий крюк: дар боли", en: "Hooked: Gift of Pain" },
  { ru: "Мрачные объятья", en: "Grim Embrace" },
  { ru: "Секущий крюк: резонанс боли", en: "Hooked: Resonance of Pain" },
  { ru: "Порча: пентименто", en: "Hex: Pentimento" },
  { ru: "Соленое море", en: "Salty Sea" },
  { ru: "Секущий крюк: пучина ярости", en: "Hooked: Abyss of Rage" },
  { ru: "Безжалостный шторм", en: "Merciless Storm" },
  { ru: "Растворение", en: "Dissolution" },
  { ru: "Явление мрака", en: "Manifestation of Darkness" },
  { ru: "Тлетворное касание", en: "Putrid Touch" },
  { ru: "Лучшая анатомия", en: "Best Anatomy" },
  { ru: "Развитая внимательность", en: "Enhanced Awareness" },
  { ru: "Последний этап", en: "Final Stage" },
  { ru: "Им не укрыться", en: "No Hiding" },
  { ru: "Порча: лик мрака", en: "Hex: Face of Darkness" },
  { ru: "Свирепая гордыня", en: "Fierce Pride" },
  { ru: "Бац!", en: "Bam!" },
  { ru: "Рычаг влияния", en: "Lever of Influence" },
  { ru: "Догонялки", en: "Tagging" },
  { ru: "Генетические ограничения", en: "Genetic Limitation" },
  { ru: "Вынужденная нерешительность", en: "Forced Hesitation" },
  { ru: "Машинное обучение", en: "Machine Learning" },
  { ru: "Совершенное оружие", en: "Perfect Weapon" },
  { ru: "Быстрая жестокость", en: "Rapid Cruelty" },
  { ru: "Инстинкт чужого", en: "Alien Instinct" },
  { ru: "Порча: игра для двоих", en: "Hex: Game for Two" },
  { ru: "Друзья до гроба", en: "Friends 'Til the End" },
  { ru: "Батарейки в комплекте", en: "Batteries Included" },
  { ru: "Свободный", en: "Free" },
  { ru: "Непредвиденное", en: "Unexpected" },
  { ru: "Незавершенное", en: "Unfinished" },
  { ru: "Связь с плетением", en: "Connection to the Weave" },
  { ru: "Безжизненное касание", en: "Lifeless Touch" },
  { ru: "Темное высокомерие", en: "Dark Arrogance" },
  { ru: "Алчность", en: "Greed" },
  { ru: "Владычество", en: "Domination" },
  { ru: "Порча: горькая участь", en: "Hex: Bitter Fate" },
  { ru: "Оглушительный гром", en: "Deafening Thunder" },
  { ru: "Секущий крюк: щербатый компас", en: "Hooked: Broken Compass" },
  { ru: "Без пощады", en: "No Mercy" },
  { ru: "Тихий шорох", en: "Quiet Whisper" },
  { ru: "Охотник на оленей", en: "Deer Hunter" },
  { ru: "Сеющий страх", en: "Fearmonger" },
  { ru: "Коварство", en: "Deception" },
  { ru: "Мертвая хватка", en: "Death Grip" },
  { ru: "Секущий крюк: чудовищный храм", en: "Hooked: Monstrous Temple" },
  { ru: "Порча: никому не скрыться от смерти", en: "Hex: No One Escapes Death" },
  { ru: "Небрежный мясник", en: "Careless Butcher" },
  { ru: "Сумеречные шпионы", en: "Twilight Spies" },
  { ru: "Порча: охотничий азарт", en: "Hex: Hunting Frenzy" },
  { ru: "Безжалостный", en: "Ruthless" },
  { ru: "Шепоты", en: "Whispers" },
  { ru: "Разбитые надежды", en: "Broken Hopes" }
];