export const SURVIVORS = [
  { name: "Dwight Fairfield | Дуайт Фэйрфилд", avatar: "/images/avatars/dwight.webp" },
  { name: "Meg Thomas | Мэг Томас", avatar: "/images/avatars/meg.webp" },
  { name: "Claudette Morel | Клодетт Морель", avatar: "/images/avatars/claud.webp" },
  { name: "Jake Park | Джейк Парк", avatar: "/images/avatars/jake.webp" },
  { name: "Nea Karlsson | Нея Карлссон", avatar: "/images/avatars/nea.webp" },
  { name: "Laurie Strode | Лори Строуд", avatar: "/images/avatars/lori.webp" },
  { name: "Ace Visconti | Эйс Висконти", avatar: "/images/avatars/ace.webp" },
  { name: "William 'Bill' Overbeck | Уильям 'Билл' Овербек", avatar: "/images/avatars/will.webp" },
  { name: "Feng Min | Фенг Мин", avatar: "/images/avatars/feng.webp" },
  { name: "David King | Дэвид Кинг", avatar: "/images/avatars/david.webp" },
  { name: "Quentin Smith | Квентин Смит", avatar: "/images/avatars/kventin.webp" },
  { name: "Detective David Tapp | Детектив Тэпп", avatar: "/images/avatars/detective.webp" },
  { name: "Kate Denson | Кейт Денсон", avatar: "/images/avatars/kate.webp" },
  { name: "Adam Francis | Адам Фрэнсис", avatar: "/images/avatars/adam.webp" },
  { name: "Jeff Johansen | Джефф Йохансен", avatar: "/images/avatars/jeff.webp" },
  { name: "Jane Romero | Джейн Ромеро", avatar: "/images/avatars/jane.webp" },
  { name: "Ashley J. Williams | Эшли Джей Уильямс", avatar: "/images/avatars/ash.webp" },
  { name: "Steve Harrington | Стив Харрингтон", avatar: "/images/avatars/steve.webp" },
  { name: "Nancy Wheeler | Нэнси Уиллер", avatar: "/images/avatars/nancy.webp" },
  { name: "Yui Kimura | Юи Кимура", avatar: "/images/avatars/yui.webp" },
  { name: "Zarina Kassir | Зарина Кассир", avatar: "/images/avatars/zarina.webp" },
  { name: "Cheryl Mason | Шерил Мейсон", avatar: "/images/avatars/sheril.webp" },
  { name: "Felix Richter | Феликс Рихтер", avatar: "/images/avatars/felix.webp" },
  { name: "Elodie Rakoto | Элоди Ракото", avatar: "/images/avatars/elodi.webp" },
  { name: "Yun Jin Lee | Ли Юнчин", avatar: "/images/avatars/li.webp" },
  { name: "Jill Valentine | Джилл Валентайн", avatar: "/images/avatars/jill.webp" },
  { name: "Leon S. Kennedy | Леон С. Кеннеди", avatar: "/images/avatars/leon.webp" },
  { name: "Mikaela Reed | Микаэла Рид", avatar: "/images/avatars/mikaela.webp" },
  { name: "Jonah Vasquez | Хонас Васкес", avatar: "/images/avatars/honas.webp" },
  { name: "Yoichi Asakawa | Ёити Асакава", avatar: "/images/avatars/eiti.webp" },
  { name: "Haddie Kaur | Хэдди Каур", avatar: "/images/avatars/haddy.webp" },
  { name: "Ada Wong | Ада Вонг", avatar: "/images/avatars/ada.webp" },
  { name: "Rebecca Chambers | Ребекка Чемберс", avatar: "/images/avatars/rebecca.webp" },
  { name: "Vittorio Toscano | Витторио Тоскано", avatar: "/images/avatars/vittorio.webp" },
  { name: "Thalita Lyra | Талита Лира", avatar: "/images/avatars/talita.webp" },
  { name: "Renato Lyra | Ренато Лира", avatar: "/images/avatars/renato.webp" },
  { name: "Gabriel Soma | Габриэль Сома", avatar: "/images/avatars/habriel.webp" },
  { name: "Nicolas Cage | Николас Кейдж", avatar: "/images/avatars/cage.webp" },
  { name: "Ellen Ripley | Эллен Рипли", avatar: "/images/avatars/eplen.webp" },
  { name: "Alan Wake | Алан Уэйк", avatar: "/images/avatars/alan.webp" },
  { name: "Sable Ward | Сейбл Уорд", avatar: "/images/avatars/sable.webp" },
  { name: "The Troupe | Аэстри Язар", avatar: "/images/avatars/aestri.webp" },
  { name: "Lara Croft | Лара Крофт", avatar: "/images/avatars/lara.webp" },
  { name: "Trevor Belmont | Тревор Бельмонт", avatar: "/images/avatars/trevor.webp" },
  { name: "Tauri Cain | Тори Кейн", avatar: "/images/avatars/tori.webp" }
];
