export const SURVIVORS_PERKS = [
  { ru: 'Связь', en: 'Bond' },
  { ru: 'Прояви себя', en: 'Prove Thyself' },
  { ru: 'Лидер', en: 'Leader' },
  { ru: 'Спокойствие духа', en: 'Calm Spirit' },
  { ru: 'Железная воля', en: 'Iron Will' },
  { ru: 'Крушитель', en: 'Saboteur' },
  { ru: 'Ловкое приземление', en: 'Balanced Landing' },
  { ru: 'Городской бег', en: 'Urban Evasion' },
  { ru: 'Уроки улиц', en: 'Streetwise' },
  { ru: 'Туз в рукаве', en: 'Ace in the Hole' },
  { ru: 'Повысить ставки', en: 'Up the Ante' },
  { ru: 'Игра в открытую', en: 'Open-Handed' },
  { ru: 'Познания в ботанике', en: 'Botany Knowledge' },
  { ru: 'Сострадание', en: 'Empathy' },
  { ru: 'Сам себе доктор', en: 'Self-Care' },
  { ru: 'Адреналин', en: 'Adrenaline' },
  { ru: 'Быстрый и тихий', en: 'Quick and Quiet' },
  { ru: 'Спринтер', en: 'Sprint Burst' },
  { ru: 'Единственный выживший', en: 'Sole Survivor' },
  { ru: 'Решающий удар', en: 'Decisive Strike' },
  { ru: 'Объект одержимости', en: 'Object Obsession' },
  { ru: 'Одолженное время', en: 'Borrowed Time' },
  { ru: 'Оставленный позади', en: 'Left Behind' },
  { ru: 'Несокрушимый', en: 'Unbreakable' },
  { ru: 'Тревога', en: 'Alert' },
  { ru: 'Гибкость', en: 'Lithe' },
  { ru: 'Техник', en: 'Technician' },
  { ru: 'Мы будем жить вечно', en: 'We’re Gonna Live Forever' },
  { ru: 'Крепкий орешек', en: 'Dead Hard' },
  { ru: 'Без сожаления', en: 'No Mither' },
  { ru: 'Аптекарь', en: 'Pharmacy' },
  { ru: 'Бессонница', en: 'Vigil' },
  { ru: 'Проснись', en: 'Wake Up' },
  { ru: 'Выдержка', en: 'Tenacity' },
  { ru: 'Детективное чутье', en: 'Detective’s Hunch' },
  { ru: 'Выслеживание подозреваемого', en: 'Stake Out' },
  { ru: 'Потанцуй со мной', en: 'Dance With Me' },
  { ru: 'Уникальная возможность', en: 'Windows of Opportunity' },
  { ru: 'Через край', en: 'Boil Over' },
  { ru: 'Самоучка', en: 'Autodidact' },
  { ru: 'Освобождение', en: 'Deliverance' },
  { ru: 'Диверсия', en: 'Diversion' },
  { ru: 'Уход за больным', en: 'Aftercare' },
  { ru: 'Поломка', en: 'Breakdown' },
  { ru: 'Искажение', en: 'Distortion' },
  { ru: 'Солидарность', en: 'Solidarity' },
  { ru: 'Равновесие', en: 'Poised' },
  { ru: 'Напролом', en: 'Head On' },
  { ru: 'Раскачка', en: 'Flip-Flop' },
  { ru: 'Пристегнись', en: 'Buckle Up' },
  { ru: 'Проверка на прочность', en: 'Mettle of Man' },
  { ru: 'Нянька', en: 'Baby-Sitter' },
  { ru: 'Товарищество', en: 'Camaraderie' },
  { ru: 'Второе дыхание', en: 'Second Wind' },
  { ru: 'Лучше вместе', en: 'Better Together' },
  { ru: 'Фиксация', en: 'Fixated' },
  { ru: 'Внутренняя сила', en: 'Inner Strength' },
  { ru: 'Любыми средствами', en: 'Any Means Necessary' },
  { ru: 'Форсаж', en: 'Breakout' },
  { ru: 'Везение', en: 'Lucky Break' },
  { ru: 'Ради людей', en: 'For the People' },
  { ru: 'Обман во благо', en: 'Red Herring' },
  { ru: 'Без огласки', en: 'Off the Record' },
  { ru: 'Оберег души', en: 'Soul Guard' },
  { ru: 'Кровавый договор', en: 'Blood Pact' },
  { ru: 'Скрытый союз', en: 'Repressed Alliance' },
  { ru: 'Строим на века', en: 'Built to Last' },
  { ru: 'Отчаянные меры', en: 'Desperate Measures' },
  { ru: 'Визионер', en: 'Visionary' },
  { ru: 'Изучение', en: 'Appraisal' },
  { ru: 'Уловка', en: 'Deception' },
  { ru: 'Отчаянная борьба', en: 'Power Struggle' },
  { ru: 'За чужой счет', en: 'Fast Track' },
  { ru: 'Ударный забег', en: 'Smash Hit' },
  { ru: 'Самосохранение', en: 'Self-Preservation' },
  { ru: 'Стиснув зубы', en: 'Bite the Bullet' },
  { ru: 'Световая граната', en: 'Flashbang' },
  { ru: 'Дух новичка', en: 'Rookie Spirit' },
  { ru: 'Фугасная мина', en: 'Blast Mine' },
  { ru: 'Поправка', en: 'Resurgence' },
  { ru: 'Противодействие', en: 'Counterforce' },
  { ru: 'Ясновидение', en: 'Clairvoyance' },
  { ru: 'Дар: круг исцеления', en: 'Boon: Circle of Healing' },
  { ru: 'Дар: уход в тень', en: 'Boon: Shadow Step' },
  { ru: 'Преодоление', en: 'Overcome' },
  { ru: 'Корректировка', en: 'Corrective Action' },
  { ru: 'Дар: экспонента', en: 'Boon: Exponential' },
  { ru: 'Дар: теория мрака', en: 'Boon: Dark Theory' },
  { ru: 'Эмпатическая связь', en: 'Boon: Empathic Connection' },
  { ru: 'Родительская забота', en: 'Boon: Parental Guidance' },
  { ru: 'Собранность', en: 'Inner Focus' },
  { ru: 'Остаточное проявление', en: 'Residual Manifest' },
  { ru: 'Усердие', en: 'Overzealous' },
  { ru: 'Жучок', en: 'Wiretap' },
  { ru: 'Ниже травы', en: 'Low Profile' },
  { ru: 'Поспешное лечение', en: 'Reactive Healing' },
  { ru: 'Как новенький', en: 'Better Than New' },
  { ru: 'Ободрение', en: 'Reassurance' },
  { ru: 'Полная сосредоточенность', en: 'Hyperfocus' },
  { ru: 'Потенциальная энергия', en: 'Potential Energy' },
  { ru: 'Умудренный туманом', en: 'Fogwise' },
  { ru: 'Быстрый гамбит', en: 'Vittorio’s Gambit' },
  { ru: 'На волю', en: 'Cut Loose' },
  { ru: 'Командная работа: быстрая пара', en: 'Teamwork: Power of Two' },
  { ru: 'Дружеское состязание', en: 'Friendly Competition' },
  { ru: 'Запасной игрок', en: 'Background Player' },
  { ru: 'Командная работа: общая скрытность', en: 'Teamwork: Collective Stealth' },
  { ru: 'Выше головы', en: 'Blood Rush' },
  { ru: 'Ремонтник', en: 'Troubleshooter' },
  { ru: 'Призвание', en: 'Made for This' },
  { ru: 'Утилизатор', en: 'Scavenger' },
  { ru: 'Драматургия', en: 'Dramaturgy' },
  { ru: 'Партнер по сцене', en: 'Scene Partner' },
  { ru: 'Вот это поворот', en: 'Plot Twist' },
  { ru: 'Счастливая звезда', en: 'Lucky Star' },
  { ru: 'Химическая ловушка', en: 'Chemical Trap' },
  { ru: 'Легкоступ', en: 'Light-Footed' },
  { ru: 'Воин света', en: 'Champ of Light' },
  { ru: 'Дар: освещение', en: 'Illumination' },
  { ru: 'Дедлайн', en: 'Deadline' },
  { ru: 'Чары: пауки-прядильщики', en: 'Invocation: Weaving Spiders' },
  { ru: 'Сила во мраке', en: 'Strength in Shadows' },
  { ru: 'Дерзость', en: 'Wicked' },
  { ru: 'Зеркальная иллюзия', en: 'Mirrored Illusion' },
  { ru: 'Вдохновение барда', en: 'Bardic Inspiration' },
  { ru: 'Замри и увидишь', en: 'Still Sight' },
  { ru: 'Сноровка', en: 'Finesse' },
  { ru: 'Специалист', en: 'Specialist' },
  { ru: 'Закалка', en: 'Hardened' },
  { ru: 'Глаза Бельмонта', en: 'Eyes of Belmont' },
  { ru: 'Ликование', en: 'Exultation' },
  { ru: 'Момент славы', en: 'Moment of Glory' },
  { ru: 'Чары: предательские вороны', en: 'Invocation: Treacherous Crows' },
  { ru: 'С чистого листа', en: 'Clean Break' },
  { ru: 'Бремя на себя', en: 'Shoulder the Burden' },
  { ru: 'Темное чувство', en: 'Dark Sense' },
  { ru: 'Дежавю', en: 'Déjà Vu' },
  { ru: 'Надежда', en: 'Hope' },
  { ru: 'Кровные узы', en: 'Kindred' },
  { ru: 'Легковес', en: 'Lightweight' },
  { ru: 'Этому не бывать', en: 'This is Not Happening' },
  { ru: 'Мы справимся', en: 'We’ll Make It' },
  { ru: 'Предчувствие', en: 'Premonition' },
  { ru: 'Устойчивость', en: 'Resilience' },
  { ru: 'Скользкое мясо', en: 'Slippery Meat' },
  { ru: 'Мелкая дичь', en: 'Small Game' },
  { ru: 'Мурашки по спине', en: 'Spine Chill' },
  { ru: 'Никто не остался позади', en: 'No One Left Behind' },
  { ru: 'Приключение', en: 'Adrenaline Junkie' },
  { ru: 'Настроенность', en: 'Mindset' },
  { ru: 'Без страха', en: 'Fearless' },
  { ru: 'В одиночку', en: 'On My Own' },
  { ru: 'Покоритель препятствий', en: 'Obstacle Master' }
];
